### ISSUE TITLE
Using Amazon S3

### ISSUE THREAD

**Issue by oleteacher** [kofon95/smartuploader#1]
Really like the simplicity of your smart uploader, great job.

I am confused on how to setup amazon s3 within the js files. Looking at examples is not helping me to understand. Did not see anything on wiki?

Could you explain where I would enter my Amazon S3 info?

Thank you.

**Comment by sagidM** [comment]
@oleteacher,
Thank you question.

I just make post request to Amazon S3.
So, you need to allow files:
Choose your bucket, click to "Permissions" tab, in "Public access" you have what you need.

This photo may help
![2017-08-25 09-41-14](https://user-images.githubusercontent.com/13490595/29702534-5d374cc8-897a-11e7-8640-affa2263f2c9.png)

You can use this simple form to upload any file
```html
  <form action="http://[YOUR_BUCKET_NAME].s3.amazonaws.com" method="post" enctype="multipart/form-data">
  	<input type="text" name="key" value="my file's name here">
  	<input type="file" name="file">
  	<input type="submit" >
  </form>
```

Hope it helped

***

**UPD**
As far as I know, Amazon allow upload only one file in one request.
And **key** always must be before **file**

***

**UPD**

I almost forgot.
It's unsecure method because every person can upload their files and replace yours!
So you should **pre-sign** your request with special key. This _key_ is created on server side (it also contains path to file).

Once, this link helped me
https://devcenter.heroku.com/articles/direct-to-s3-image-uploads-in-rails#pre-signed-post
Even if you don't use _Heroku_ or _Ruby on Rails_, reading this article should help.

For other languages you can use search on Heroku.
And also see the official docs
http://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html

**Comment by kofon95** [comment]
I almost forgot. It's unsecure method because every person can upload their files and replace yours!

So you should ****

**Comment by oleteacher** [comment]
Thank you much for reply and input @kofon95 

I was under impression that your script was setup to use amazon key & secret. I will explore to see if can use as is.

Thank you again.

**Comment by sagidM** [comment]
You're very welcome
